#!/bin/sh
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

version=$(cat /etc/ops-toolbelt/VERSION)
sed -e "s/\${version}/$version/" /usr/local/bin/help-toolbelt.txt
echo ""